# Generated by Django 4.2.4 on 2023-08-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_modified_date',
        ),
        migrations.AddField(
            model_name='product',
            name='date_last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Last Updated'),
        ),
    ]
