# Generated by Django 4.2.4 on 2023-08-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_product_last_modified_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category', 'description'), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
    ]
