# Generated by Django 4.2.4 on 2023-08-24 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_category_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'category', 'price', 'date_created', 'in_stock'), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
