# Generated by Django 4.2.4 on 2023-09-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_version_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.IntegerField(max_length=10, verbose_name='Version Number'),
        ),
    ]
