# Generated by Django 4.2.4 on 2023-09-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_version_version_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.CharField(max_length=10, verbose_name='Version Number'),
        ),
    ]
